[build]
target = "riscv64gc-unknown-none-elf"
# target = "loongarch64-unknown-none"

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-Clink-arg=-Tsrc/hal/arch/riscv/linker.ld",
    "-Cforce-frame-pointers=yes",
    "-Clink-arg=-static",
]

[target.loongarch64-unknown-none]
rustflags = [
    "-Clink-arg=-Tsrc/hal/arch/loongarch/linker.ld",
    "-Cforce-frame-pointers=yes",
]